FROM ubuntu:bionic

ENV UWSGI_MODULE=radiograph.wsgi
ENV UWSGI_WORKERS=8
ENV UWSGI_HTTP_SOCKET=:5000
ENV SECRET_KEY="<fill at runtime>"

RUN apt update && apt install -y python-pip libpq-dev
COPY . /opt/radiograph
WORKDIR /opt/radiograph
RUN pip install -r requirements.txt
RUN python ./manage.py collectstatic --noinput

EXPOSE 5000

CMD uwsgi
