---
# 
# Standard configuration for all servers.  Installs minimal dependencies needed
# to pull and build code, run services, and run common ansible actions remotely.
#
- hosts: all
  sudo: true

  tasks:
  - include: sudo/plays/init.yml

  - name: install base system dependencies
    yum: name=${item} state=present
    with_items:
    - gcc
    - git

  - include: python/plays/install.yml
  - include: supervisor/plays/install.yml

  - name: install ansible module python dependencies
    pip: name=${item} state=present
    with_items:
    - httplib2  # needed for uri action
