---
- name: dump database on the remote node
  shell: pg_dump $database | gzip > /tmp/$database.sql.gz
  sudo: true
  sudo_user: postgres

- name: retrieve database dump to local machine
  fetch: src=/tmp/$database.sql.gz
         dest=$dest

