---
- name: install dependencies
  yum: name=$item
  with_items:
    - postgresql-server
    - postgresql-devel
    - python-psycopg2

- name: install psycopg2 to enable ansible postgres actions
  pip: name=psycopg2 state=present

- name: ensure that postgres is initialized
  command: ${postgresql.service_script} initdb creates=${postgresql.data_dir}/postgresql.conf

- name: create conf.d directory for assembling pg_hba.conf
  file: name=${postgresql.data_dir}/pg_hba.conf.d state=directory owner=postgres

- name: add basic pg_hba.conf contents
  template: src=postgresql/templates/pg_hba.conf dest=${postgresql.data_dir}/pg_hba.conf.d/001-pg_hba.conf-basic
  notify:
  - assemble postgres auth file
  - reload postgres

- name: ensure that postgres is running and registered as a startup service
  service: name=postgresql state=started enabled=true
