---
- name: create database
  postgresql_db: db=$name
  sudo: true
  sudo_user: postgres

- name: ensure user has database access
  postgresql_user: db=$name user=$user password=$password priv=ALL
  sudo: true
  sudo_user: postgres

- name: ensure user does not have unnecessary privileges
  postgresql_user: user=$user role_attr_flags=NOSUPERUSER,NOCREATEDB
  sudo: true
  sudo_user: postgres

# Create a pg_hba.conf fragment with the provided auth_rules, which will be
# assembled to create the full pg_hba.conf file.
#   
# Sample auth_rules list:
# vars:
#   auth_rules:
#    - type: local
#      database: all
#      user: all
#      address: 127.0.0.1
#      method: trust
#      method_options: ?
#

- name: create auth rules
  template: src=postgresql/templates/auth_rules.j2 dest=${postgresql.data_dir}/pg_hba.conf.d/$name owner=postgres
  notify:
  - assemble postgres auth file
  - reload postgres

