---
#
# Dependencies
# + Python and pip, which can be installed with the include line:
#
#   - include: python/plays/install.yml
#

- name: install supervisor
  pip: name=supervisor

- name: configure supervisord
  template: src=supervisor/templates/supervisord.conf dest=/etc/supervisord.conf

- name: create conf.d directory
  file: name=/etc/supervisor/conf.d state=directory

- name: create supervisord init script
  template: src=supervisor/templates/init
            dest=/etc/init.d/supervisord
            mode=0755

- name: add supervisord sysconfig settings
  template: src=supervisor/templates/sysconfig
            dest=/etc/sysconfig/supervisord
            mode=0755

- name: register supervisord service
  command: chkconfig --add supervisord

- name: ensure that supervisord is running and will run at startup
  service: name=supervisord
           enabled=true
           state=started
